title:              부빠기
email:              buppagi@meilcoding.com
description:        매일 매일 마크업 코딩하는 UI개발자 부빠기입니다.
author:             buppagi
baseurl:            ""
url:                "http://www.buppagi.com"

# Social Profiles
twitter_username:   
github_username:    buppagi
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-176873649-1 # out your google-analytics code

# Build settings
markdown:           kramdown
permalink:          /:year/:categories/:title
#paginate:           5
#paginate_path:      /page/:num
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

# Paginate config
pagination:
  enabled: true
  collection: posts
  per_page: 5
  sort_reverse: true
  title: ':title'
  permalink: '/page/:num/'
  trail: 
    before: 2
    after: 2

tipue_search:
  include:
      pages: false
      collections: []
  exclude:
      files: [search.html, index.html, tags.html]
      categories: []
      tags: []




category_list: [ 유익한 정보, UI 개발, 개발도구, TIL]