title:              부빠기
email:              buppagi@meilcoding.com
description:        매일 매일 마크업 코딩하는 UI개발자 부빠기입니다.
author:             buppagi
baseurl:            ""
url:                "http://www.buppagi.com"

# Social Profiles
twitter_username:   
github_username:    buppagi
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           10
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
